### PR TITLE
Added script to `package.json` for `npm start` to work.

### PR DESCRIPTION
**Pull request by mik01aj**
It is a standard way to run stuff in npm: https://docs.npmjs.com/misc/scripts

### CODE REVIEW

**Comment by mik01aj** [comment]
I just realized that this doesn't make much sense without adding `sourcejs` to `dependencies`. Is there any reason why it isn't there?

If it were, the installation and starting would be pretty standard: `npm install && npm start`.

**Comment by operatino** [comment]
Hi, Mikołaj!

SourceJS as npm dependecy support was landed quite recently, with 0.5.3 version release. But it's not yet very stable, and we want to test it a bit more, also we still need to fix `npm link` workflow, which is not yet working.

With 0.6.0 the official install path will be exactly as you mentioned - `npm install sourcejs && npm start`. We just want to test it a bit more, but feel free to use is this way.

BTW, I remember you asked about React integration, here's a plugin made by other contributor https://www.npmjs.com/package/sourcejs-react.

**Comment by mik01aj** [comment]
Thanks, @operatino!

I saw the plugin, and even already reported an issue on it! I'd like to extend it in the future (given enough free time) :)

**Comment by operatino** [comment]
Cool, looking forward for your help!

And another thing, about the project you presented, isn't it the same as FB Relay? http://facebook.github.io/react/blog/2015/02/20/introducing-relay-and-graphql.html

**Comment by mik01aj** [comment]
It is similar, but much simpler. My squirrel was actually inspired by GraphQL. The facebook devs did a great presentation about the problem.

Unfortunately, I have to say that I had to take the repo down because it turns out that in our company it is still not clear who really owns the code :cry:  I hope this bureucracy ends soon and squirrel will be finally released.

**Pull request closed without merging**
